# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    gaps_in = 4
    gaps_out = 5
    border_size = 3
    col.active_border = rgba(cca07aee) rgba(b88a7aee) 45deg
    col.inactive_border = rgba(4a4440aa)
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    rounding = 8

    active_opacity = 0.90
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0

    dim_inactive = false
    dim_strength = 0.15

    shadow {
        enabled = true
        range = 4
        render_power = 2
        color = rgba(1a1a1aee)
        offset = 0 3
        scale = 0.97
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        new_optimizations = true
        special = true
        brightness = 0.60
        contrast = 0.75
    }
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    enabled = yes

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = windows, 1, 4, easeOutQuint
    animation = windowsIn, 1, 4, easeOutQuint, popin 85%
    animation = windowsOut, 1, 1.5, linear, popin 85%
    animation = fade, 1, 3, quick
    animation = fadeIn, 1, 2, almostLinear
    animation = fadeOut, 1, 1.5, almostLinear
    animation = layers, 1, 4, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = workspaces, 1, 3, easeOutQuint, slide
    animation = specialWorkspace, 1, 3, easeOutQuint, slidevert
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}

layerrule = blur on, ignore_alpha 0, xray 1, dim_around on, match:namespace walker
