#!/bin/bash

WALLPAPER_DIR="/home/vaibhav/Downloads/wallpaper"
STATE_FILE="/tmp/wallpaper-cycle-index"
INTERVAL=600

mapfile -t WALLPAPERS < <(find "$WALLPAPER_DIR" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.bmp' -o -iname '*.webp' \) | sort)

if [ ${#WALLPAPERS[@]} -eq 0 ]; then
  exit 1
fi

if [ -f "$STATE_FILE" ]; then
  INDEX=$(cat "$STATE_FILE")
else
  INDEX=0
fi

while true; do
  WALLPAPER="${WALLPAPERS[$INDEX]}"
  killall swaybg 2>/dev/null
  swaybg -i "$WALLPAPER" -m fill &>/dev/null &
  INDEX=$(( (INDEX + 1) % ${#WALLPAPERS[@]} ))
  echo "$INDEX" > "$STATE_FILE"
  sleep "$INTERVAL"
done
